config/routes.rb
Rails.application.routes.draw do
  get 'sample_items/index'
  root "sample_items#index"

  resources :sample_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sample_item.rb
class SampleItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sample_items_controller.rb
class SampleItemsController < ApplicationController
  def index
    @sample_items = SampleItem.order(:name)
  end
  
  def new
    @sample_item = SampleItem.new
  end
  
  def show
    @sample_item = SampleItem.find(params[:id])
  end
  
  def create
    @sample_item = SampleItem.new(sample_item_params)
    if @sample_item.save
      redirect_to sample_items_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  private
  def sample_item_params
    params.require(:sample_item).permit(:name, :description, :extra_info)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sample_item_helper.rb
module SampleItemHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormTester</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sample_items/index.html.erb
<h1>Items Available</h1>
<%= button_to "Add Item", new_sample_item_path, method: :get %>

<ul>
  <% @sample_items.each do |item| %>
    <li>
      <%= link_to item.name, sample_item_path(item) %>
    </li>
  <%end%>
</ul>

app/views/sample_items/new.html.erb
<h1>Sample Item Add</h1>

<%= form_with model: @sample_item do |f| %>
  <p>
    <%= f.label :name%>
    <%= f.text_field :name%>
  </p>
  <p>
    <%= f.label :description%>
    <%= f.text_field :description%>
  </p>
  <p>
    <%= f.label :extra_info%>
    <%= f.text_field :extra_info%>
  </p>
  <%= f.submit %>
<%end%>